version: '3.8'

services:
  edith-qa:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - PERPLEXICA_URL=http://perplexica:3000/api/search
    volumes:
      - ./logs:/app/logs
      - ./images:/app/images
      - ./config:/app/config
    restart: unless-stopped
    depends_on:
      - perplexica
    networks:
      - edith-network

  android-emulator:
    image: budtmo/docker-android:emulator_11.0
    privileged: true
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5555:5555"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    volumes:
      - android-storage:/root/android_emulator
    networks:
      - edith-network
    depends_on:
      - edith-qa

  perplexica:
    image: perplexica/perplexica:latest
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - perplexica-data:/app/data
    networks:
      - edith-network
    restart: unless-stopped

volumes:
  android-storage:
  perplexica-data:

networks:
  edith-network:
    driver: bridge
